sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - 3.6-dev
  - 3.7-dev
  - pypy
  - pypy3
  - nightly
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - "pip install -e ."
    - "pip install 'coverage>=3.7,<3.8' coveralls"
script:
    - "PYTHONFAULTHANDLER=x timeout -sABRT 30s nosetests -vsd"
after_success:
    - coveralls

deploy:
  provider: pypi
  user: "repeatedly"
  password:
    secure: "ePNUJvw76/pGM+c++vJ1Qa2a2/PZ0bWc04So9ZRTxlOWao4+ZgldsKqqFUps3NqyfddNUDwkoz7mNwJGMcLnkAJK9dhobolIdyMEVke1iQkXEJAuxQ6I3ezZp2wRYOfIl7+ztqXauZA5DflXVnfeOfPZpzvwLsFClFlklyCfWJM="
  on:
    tags: true
    condition: '"$TRAVIS_PYTHON_VERSION" = "3.6" || "$TRAVIS_PYTHON_VERSION" = "2.7"'
  distributions: "sdist bdist_wheel"

matrix:
  allow_failures:
    - python: nightly
